---
title: "Climate and landuse suitability"
author: ""
date: ""
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```



```{r niche_map, include=FALSE}
#library(biomod2)
library(raster)
library(leaflet)
library(rgdal)
library(leafem)



# all_spp <- c("cactorum",
#             "cambivora",
#             "cinnamomi",
#             "cryptogea",
#             "gonapodyides",
#             "lacustris",
#             "plurivora",
#             "ramorum",
#             "alni")
species <- "ramorum"


  UK_validation <- readOGR("data", layer="UK_validation")
  UK_validation <- UK_validation[grep(species, UK_validation$species),]
  
  r <- raster(grep("current\\.tif", list.files(pattern = species, recursive = TRUE), value = TRUE)[1])

  extUK <- c(-495000, 130000, 5800000, 6900000)
  r <- crop(r, extUK)
  
  UK_validation <- crop(UK_validation, extUK)
  UK_validation <- spTransform(UK_validation, crs("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))
  #UK_validation <- spTransform(UK_validation, crs("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))
  r <- projectRaster(from = r, crs = crs("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"), method = "bilinear")
  # 
  # r_polys <- rasterToPolygons(r)
  # r_polys <- spTransform(r_polys, crs("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))
  # 
  #m <- mapview(r, layer.name = c(paste0("P. ", species, " suitability")))
  #m@map  %>% addTiles()  %>% leafem::addImageQuery(r, "values")
  #+ mapview(UK_validation, layer.name = paste0("P. ", species, " records")) + leafpop::popupTable(x = UK_validation, zcol = "host", row.numbers = FALSE)
  #layer.name = c(paste0("P. ", species, " suitability"), paste0("P. ", species, " records"))
  #m
  #+ mapview(validation, layer.name = "UK validation data")
  
  #cntr_crds <- c(mean(coordinates(r_crop)[, 1]),
  #               mean(coordinates(r_crop)[, 2]))
  #m@map %>% setView(cntr_crds[1], cntr_crds[2], zoom = 2)
  #mapshot(m, url = paste0("_site/", all_spp[i], ".html"))

```

###*Phytophthora `r species`*
```{r fig.width = 10, error=FALSE, warning=FALSE}

# leafletem not working so I can't add mouseover for suitability values
pal <- colorNumeric(c("blue", "white", "red"), values(r),   na.color = "transparent")
# UK_points$nursery_widerEnvironment <- factor(UK_points$nursery_widerEnvironment)
# pal <- colorFactor(c("navy", "red"), domain = c("nursery", "wider environment"))

 leaflet(UK_validation, width = "100%") %>% 
   addProviderTiles("OpenTopoMap") %>% #, options = providerTileOptions(minZoom=5, maxZoom=10)) %>%
   addCircleMarkers(radius = 4,
                    stroke = FALSE, 
                    fillOpacity = 0.5,
                    label = ~host,
                    color = "black", 
                    group = paste0("P. ", species, " records")) %>%
   addRasterImage(r, colors = pal, opacity = 0.8, group = paste0("P. ", species, " suitability"), layerId = paste0("P. ", species, " suitability")) %>% 
   addLegend(pal = pal, values = values(r),
             group = paste0("P. ", species, " suitability"),
              title = paste0("P. ", species, " suitability")) %>%
    addLegend(data = UK_validation,
              colors = "black",
              labels = paste0("P. ", species, " records"),
              opacity = 0.9,
              title = "",
              position = "bottomleft",
              group = paste0("P. ", species, " records")) %>%
   addLayersControl(baseGroups = paste0("P. ", species, " records"),
                    overlayGroups = paste0("P. ", species, " suitability"),
                    options = layersControlOptions(collapsed = FALSE)) %>% 
   hideGroup(paste0("P. ", species, " suitability")) %>%
   leafem::addMouseCoordinates() %>% 
   addHomeButton(extent(UK_validation), layer.name = "Back to UK")  %>%
   leafem::addImageQuery(r, type="mousemove", layerId = paste0("P. ", species, " suitability"), group = paste0("P. ", species, " suitability") , digits = 3)
#pal <- colorFactor(c("white", "black"), domain = c("nursery", "wider environment"))
# m@map %>% setView(zoom = 6, lng = 0, lat = 55) %>% addCircleMarkers(data = UK_validation,
#                    #group = ~species,
#                    radius = 6,
#                    stroke = FALSE, 
#                    fillOpacity = 0.9,
#                    label = ~host, 
#                    color = "white") %>%
#     addLegend(data = UK_validation,
#               colors = "white",
#               labels = paste0("P. ", species, " records"),
#               opacity = 0.9, 
#               title = "",
#               position = "bottomleft") 
#m

```
