---
title: "Distribution of *Phytophthora* species in nurseries and the wider environment"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = getwd())
library(leaflet)
library(sp)
```


```{r cars}

UK_data <- read.csv("2019-09-13_all_UK_data_Katy.csv", stringsAsFactors = FALSE)
UK_data <- UK_data[complete.cases(UK_data[,c("longitude", "latitude")]),]
UK_data <- UK_data[UK_data$longitude > min(UK_data$longitude),]
UK_data$nursery_widerEnvironment <- gsub("Environment", "environment", UK_data$nursery_widerEnvironment)
UK_data$nursery_widerEnvironment <- gsub("Wider", "wider", UK_data$nursery_widerEnvironment)
UK_data$nursery_widerEnvironment <- gsub("Nursery", "nursery", UK_data$nursery_widerEnvironment)
UK_data <- UK_data[!is.na(UK_data$nursery_widerEnvironment),]
UK_data <- UK_data[!UK_data$species %in% "Phytophthora spp.",]
UK_points <- SpatialPointsDataFrame(coords = UK_data[,c("longitude", "latitude")],
                                    data = UK_data)
#save(UK_points, file = "UK_validation.rData")


```

```{r Uk}

UK_points$nursery_widerEnvironment <- factor(UK_points$nursery_widerEnvironment)
pal <- colorFactor(c("navy", "red"), domain = c("nursery", "wider environment"))

UK_map <- leaflet(UK_points, width = "100%") %>% 
  addProviderTiles("OpenTopoMap", options = providerTileOptions(minZoom=5, maxZoom=10)) %>%
  clearBounds() %>%
  addCircleMarkers(color = ~pal(nursery_widerEnvironment),
                   group = ~species,
                   radius = 4,
                   stroke = FALSE, 
                   fillOpacity = 0.5,
                   label = ~host) %>%
  addLayersControl(baseGroups = unique(UK_points$species),
                 options = layersControlOptions(collapsed = TRUE)) %>%
  addLegend(pal = pal, 
            values = ~nursery_widerEnvironment, 
            opacity = 0.7, 
            title = "",
            position = "bottomleft")
  

UK_map


```